
server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  application:
    name: fileManagerSystem
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.195.136:8848
        username: nacos
        group: SEATA_GROUP
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.195.136:8081

management:
  endpoint:
    web:
      exposure:
        include:'*'
