
server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: fileManagerSystem
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.195.136:8848
        username: nacos
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.195.136:8081

management:
  endpoint:
    web:
      exposure:
        include:'*'
