mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.study.hunting.domain
server:
  port: 8083
spring:
  application:
    name: baseInfoSystem
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.199.133:8848
        username: nacos
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://192.168.199.133:3306/hunting_info?serverTimezone=UTC
    username: root
  session:
    store-type: redis
    redis:
      host: 192.168.199.133
      database: 0
      port: 6379
      timeout: 3600
      lettuce.pool.max-active: 16
      lettuce.pool.max-wait: -1ms
      lettuce.pool.max-idle: 8
      lettuce.pool.min-idle: 1