mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.study.hunting.domain
server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: baseInfoSystem
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.195.136:8848
        username: nacos
        group: SEATA_GROUP
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.195.136:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://localhost:3306/hunting_info?serverTimezone=UTC
    username: root
  session:
    store-type: redis
    redis:
      host: 192.168.195.136
      database: 0
      port: 6379
      timeout: 3600
      lettuce.pool.max-active: 16
      lettuce.pool.max-wait: -1ms
      lettuce.pool.max-idle: 8
      lettuce.pool.min-idle: 1

management:
  endpoint:
    web:
      exposure:
        include:'*'
